export const EPISODES = [
  {
    title: 'Podcast No. 29. Despedida de 2023',
    name: '29',
    thumbnail: 'https://i.ytimg.com/vi_webp/4vcVYaREthI/maxresdefault.webp',
    song: 'https://firebasestorage.googleapis.com/v0/b/lavaderosonico.appspot.com/o/29.mp3?alt=media&token=',
  },
  {
    title: 'Podcast No. 28 Lower Decks Temporada 4',
    name: '28',
    thumbnail: 'https://i.ytimg.com/vi_webp/XfVhpIuCYEY/maxresdefault.webp',
    song: 'https://firebasestorage.googleapis.com/v0/b/lavaderosonico.appspot.com/o/28.mp3?alt=media&token=',
  },
  {
    title: 'Podcats No. 27 - Strange New Worlds, temporada 2',
    name: '27',
    thumbnail: 'https://i.ytimg.com/vi_webp/9rd9HCmEACU/maxresdefault.webp',
    song: 'https://firebasestorage.googleapis.com/v0/b/lavaderosonico.appspot.com/o/27.mp3?alt=media&token=',
  },
  {
    title: 'Podcast No. 26 - Picard temporada final',
    name: '26',
    thumbnail: 'https://i.ytimg.com/vi_webp/7kDEHl55Ph4/maxresdefault.webp',
    song: 'https://firebasestorage.googleapis.com/v0/b/lavaderosonico.appspot.com/o/26.mp3?alt=media&token=',
  },
  {
    title: 'Podcast No  25 Lower Decks Temporada 3',
    name: '25-1',
    thumbnail: 'https://i.ytimg.com/vi_webp/BB7bHkH3raU/maxresdefault.webp',
    song: 'https://firebasestorage.googleapis.com/v0/b/lavaderosonico.appspot.com/o/25-1.mp3?alt=media&token=',
  },
  {
    title: 'Podcast No. 25 • Star Trek Picard, temporada 2',
    name: '25',
    thumbnail: 'https://i.ytimg.com/vi_webp/RW0ijwmkeCw/maxresdefault.webp',
    song: 'https://firebasestorage.googleapis.com/v0/b/lavaderosonico.appspot.com/o/25.mp3?alt=media&token=',
  },
  {
    title: 'Podcast No. 24 Star Trek Discovery Temporada 4',
    name: '24',
    thumbnail: 'https://i.ytimg.com/vi_webp/xvfRh1ArY-8/maxresdefault.webp',
    song: 'https://firebasestorage.googleapis.com/v0/b/lavaderosonico.appspot.com/o/24.mp3?alt=media&token=',
  },
  {
    title: 'Podcast No. 23 Lower Decks Temporada 2',
    name: '23',
    thumbnail: 'https://i.ytimg.com/vi_webp/9KsFgkgtFV0/maxresdefault.webp',
    song: 'https://firebasestorage.googleapis.com/v0/b/lavaderosonico.appspot.com/o/23.mp3?alt=media&token=',
  },
  {
    title: "Podcast No. 22 'Niños Extraños'",
    name: '22',
    thumbnail: 'https://i.ytimg.com/vi_webp/1F7ngZzdyFA/maxresdefault.webp',
    song: 'https://firebasestorage.googleapis.com/v0/b/lavaderosonico.appspot.com/o/22.mp3?alt=media&token=',
  },
  {
    title: 'Podcast No. 21. Naves de otras potencias P.1',
    name: '21',
    thumbnail: 'https://i.ytimg.com/vi_webp/4UuIWLixc-g/maxresdefault.webp',
    song: 'https://firebasestorage.googleapis.com/v0/b/lavaderosonico.appspot.com/o/21.mp3?alt=media&token=',
  },
  {
    title: 'Podcast No. 20 - First Contact 2021',
    name: '20',
    thumbnail: 'https://i.ytimg.com/vi_webp/OQr0wrrMq1M/maxresdefault.webp',
    song: 'https://firebasestorage.googleapis.com/v0/b/lavaderosonico.appspot.com/o/20.mp3?alt=media&token=',
  },
  {
    title: 'Podcast No. 19 Star Trek Discovery temporada 3',
    name: '19',
    thumbnail: 'https://i.ytimg.com/vi_webp/dwaD_lGNuJ0/maxresdefault.webp',
    song: 'https://firebasestorage.googleapis.com/v0/b/lavaderosonico.appspot.com/o/19.mp3?alt=media&token=',
  },
  {
    title: 'Podcast No. 18 Lower Decks primera temporada',
    name: '18',
    thumbnail: 'https://i.ytimg.com/vi_webp/S2ZF4Tp_GnY/maxresdefault.webp',
    song: 'https://firebasestorage.googleapis.com/v0/b/lavaderosonico.appspot.com/o/18.mp3?alt=media&token=',
  },
  {
    title: 'Podcast No. 17 Un buen fin para la saga? Star Trek Nemesis',
    name: '17',
    thumbnail: 'https://i.ytimg.com/vi_webp/cO8VsRRKUAg/maxresdefault.webp',
    song: 'https://firebasestorage.googleapis.com/v0/b/lavaderosonico.appspot.com/o/17.mp3?alt=media&token=',
  },
  {
    title: 'Podcast No. 16 - A la defensa de INSURRECTION',
    name: '16',
    thumbnail: 'https://i.ytimg.com/vi_webp/56rDHKcv5Oo/maxresdefault.webp',
    song: 'https://firebasestorage.googleapis.com/v0/b/lavaderosonico.appspot.com/o/16.mp3?alt=media&token=',
  },
  {
    title: 'Podcast No. 15. Capítulos insalvables en STAR TREK',
    name: '15',
    thumbnail: 'https://i.ytimg.com/vi_webp/tguVY7FVTAw/maxresdefault.webp',
    song: 'https://firebasestorage.googleapis.com/v0/b/lavaderosonico.appspot.com/o/15.mp3?alt=media&token=',
  },
  {
    title: 'Podcast No. 14. Star Trek Picard. Revisión de la primera temporada',
    name: '14',
    thumbnail: 'https://i.ytimg.com/vi_webp/J81l36FsROo/maxresdefault.webp',
    song: 'https://firebasestorage.googleapis.com/v0/b/lavaderosonico.appspot.com/o/14.mp3?alt=media&token=',
  },
  {
    title: 'Podcast No. 13. Star Trek: First contact',
    name: '13',
    thumbnail: 'https://i.ytimg.com/vi_webp/ftnwQtiWE18/maxresdefault.webp',
    song: 'https://firebasestorage.googleapis.com/v0/b/lavaderosonico.appspot.com/o/13.mp3?alt=media&token=',
  },
  {
    title: 'Podcast No. 12. Star Trek Picard. capitulo final',
    name: '12',
    thumbnail: 'https://i.ytimg.com/vi_webp/MWSjSua-JWM/maxresdefault.webp',
    song: 'https://firebasestorage.googleapis.com/v0/b/lavaderosonico.appspot.com/o/12.mp3?alt=media&token=',
  },
  {
    title:
      'Podcast No. 11 - El Rincón del Coleccionista 1- Decipher customizable card game (ST CCG E1)',
    name: '11',
    thumbnail: 'https://i.ytimg.com/vi_webp/x7BduklVubs/maxresdefault.webp',
    song: 'https://firebasestorage.googleapis.com/v0/b/lavaderosonico.appspot.com/o/11.mp3?alt=media&token=',
  },
  {
    title: 'Podcast No.10 El Pasado en Presente Star Trek TOS',
    name: '10',
    thumbnail: 'https://i.ytimg.com/vi_webp/65vm9nEPxvE/maxresdefault.webp',
    song: 'https://firebasestorage.googleapis.com/v0/b/lavaderosonico.appspot.com/o/10.mp3?alt=media&token=',
  },
  {
    title: 'Podcast No. 9 - El Lavadero sónico - The Orville y Galaxy Quest.',
    name: '9',
    thumbnail: 'https://i.ytimg.com/vi_webp/OO2i6QnDHt0/maxresdefault.webp',
    song: 'https://firebasestorage.googleapis.com/v0/b/lavaderosonico.appspot.com/o/9.mp3?alt=media&token=',
  },
  {
    title: 'Podcast No. 8 El Lavadero Sónico - Noticias de ComiCon y STLV 2019',
    name: '8',
    thumbnail: 'https://i.ytimg.com/vi_webp/pXXVFIvhXQo/maxresdefault.webp',
    song: 'https://firebasestorage.googleapis.com/v0/b/lavaderosonico.appspot.com/o/8.mp3?alt=media&token=',
  },
  {
    title: 'Podcast No. 7 El Lavadero Express - El Canon en Star Trek',
    name: '7',
    thumbnail: 'https://i.ytimg.com/vi_webp/k3WZkCs7oc4/maxresdefault.webp',
    song: 'https://firebasestorage.googleapis.com/v0/b/lavaderosonico.appspot.com/o/7.mp3?alt=media&token=',
  },
  {
    title: 'Podcast No. 6 Star Trek Discovery, temporada 2',
    name: '6',
    thumbnail: 'https://i.ytimg.com/vi_webp/0uuVbiRSQZQ/maxresdefault.webp',
    song: 'https://firebasestorage.googleapis.com/v0/b/lavaderosonico.appspot.com/o/6.mp3?alt=media&token=',
  },
  {
    title: 'Podcast No.5 El Lavadero Sónico - Picard',
    name: '5',
    thumbnail: 'https://i.ytimg.com/vi_webp/974dFoztwUk/maxresdefault.webp',
    song: 'https://firebasestorage.googleapis.com/v0/b/lavaderosonico.appspot.com/o/5.mp3?alt=media&token=',
  },
  {
    title: 'Podcast No. 4 Hablemos de naves',
    name: '4',
    thumbnail: 'https://i.ytimg.com/vi/V1ZnjIfyQHY/hqdefault.jpg',
    song: 'https://firebasestorage.googleapis.com/v0/b/lavaderosonico.appspot.com/o/4.mp3?alt=media&token=',
  },
  {
    title: 'Podcast No. 3 Finales de serie en cine o TV.',
    name: '3',
    thumbnail: 'https://i.ytimg.com/vi_webp/2dRyEgzmh4w/maxresdefault.webp',
    song: 'https://firebasestorage.googleapis.com/v0/b/lavaderosonico.appspot.com/o/3.mp3?alt=media&token=',
  },
  {
    title: 'Podcast No.2 - Cosas que no tienen sentido en Voyager.',
    name: '2',
    thumbnail: 'https://i.ytimg.com/vi_webp/bq0ixyupq-8/maxresdefault.webp',
    song: 'https://firebasestorage.googleapis.com/v0/b/lavaderosonico.appspot.com/o/2.mp3?alt=media&token=',
  },
  {
    title: 'Podcast No.01 - Retorno al puente',
    name: '1',
    thumbnail: 'https://i.ytimg.com/vi_webp/KmlrhKOl2qY/maxresdefault.webp',
    song: 'https://firebasestorage.googleapis.com/v0/b/lavaderosonico.appspot.com/o/1.mp3?alt=media&token=',
  },
];
